#!/usr/bin/php
<?php
# @package      hubzero-metrics
# @file         xlogfix_prep
# @author       Swaroop Shivarajapura Samek <swaroop@purdue.edu>
# @copyright    Copyright (c) 2011-2015 HUBzero Foundation, LLC.
# @license      http://opensource.org/licenses/MIT MIT
#
# Copyright (c) 2011-2015 HUBzero Foundation, LLC.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# HUBzero is a registered trademark of HUBzero Foundation, LLC.
#
# =========================================================================
# This script creates an include file for the PERL scripts
#
# USAGE: ./xlogfix_setup
#

error_reporting(E_ALL & ~E_NOTICE);
@ini_set('display_errors','1');

if(!defined('__DIR__')) { 
    $fPos = strrpos(__FILE__, "/"); 
    define("__DIR__", substr(__FILE__, 0, $fPos) . "/"); 
} 

require_once(__DIR__."/includes/hub_parameters.php");

$file = __DIR__."/includes/access.cfg";

$fh = fopen($file, 'w') or die("can't open file");
$Data = "\$hub_dir = '".$hub_dir."';\n";
$Data .= "\$hub_db = '".trim($hub_db,'`')."';\n";
$Data .= "\$metrics_db = '".trim($metrics_db,'`')."';\n";
$Data .= "\$db_host = '".$db_host."';\n";
$Data .= "\$db_user = '".$db_user."';\n";
$Data .= "\$db_pass = '".$db_pass."';\n";
$Data .= "\$db_prefix = '".$db_prefix."';\n";
fwrite($fh, $Data); 
fclose($fh);

# Removing installation directory
$sh = "rm -rf ".$hub_dir."/installation";
// shell_exec($sh);

?>
