#!/usr/bin/php
<?php
# @package      hubzero-metrics
# @file         xlogfix_user_info
# @author       Swaroop Shivarajapura Samek <swaroop@purdue.edu>
# @copyright    Copyright (c) 2011-2015 HUBzero Foundation, LLC.
# @license      http://opensource.org/licenses/MIT MIT
#
# Copyright (c) 2011-2015 HUBzero Foundation, LLC.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# HUBzero is a registered trademark of HUBzero Foundation, LLC.
#
# =========================================================================
# This Script assigns countryresident, countrycitizen and orgtype to each 
# user in toolstart table
#
# USAGE: ./xlogfix_user_info
#

error_reporting(E_ALL & ~E_NOTICE);
@ini_set('display_errors','1');

if(!defined('__DIR__')) {
    $fPos = strrpos(__FILE__, "/");
    define("__DIR__", substr(__FILE__, 0, $fPos) . "/");
}

require_once(__DIR__."/includes/hub_parameters.php");
require_once(__DIR__."/includes/db_connect.php");
require_once(__DIR__."/includes/func_misc.php");

$db_hub = db_connect('db_hub');

if (!$_SERVER['argv'][1] || !$_SERVER['argv'][2])
{
	$msg = 'Usage: ' . $_SERVER['argv'][0] . '<database>.<table>'.n;
	clean_exit($msg);
}

if ($_SERVER['argv'][1] == "hub") {
	$table = $hub_db.'.'.$_SERVER['argv'][2];
} else if ($_SERVER['argv'][1] == "metrics") {
	$table = $metrics_db.'.'.$_SERVER['argv'][2];
} else {
	$msg = 'Invalid database type'.n;
	clean_exit($msg);
}

$debug = 0;
$fix_params = array('countrycitizen','countryresident','orgtype');

foreach ($fix_params as $param) {
	update_tables($db_hub, $param, $table);
}

db_close($db_hub);

function update_tables($db_hub, $param, $table) {

	global $metrics_db, $db_prefix, $debug;	
	
	if ($debug)
		print "\n".'Finding all '.$table.' records lacking '.$param.'....'."\n";

	if ($param == "countrycitizen") {
		$r_param = "countryorigin";
	} else {
		$r_param = $param;
	}
	$user_list = '';
	$sql = 'SELECT DISTINCT user FROM '.$table.' WHERE ('.$param.' = "" OR '.$param.' IS NULL)';
	$result = mysql_query($sql, $db_hub);
	if($result) {
		if(mysql_num_rows($result) > 0) {
  			while($row = mysql_fetch_assoc($result)) {
				$user_list .= '"'.$row['user'].'",';
			}
		}
	} else {
		$msg = mysql_error($db_hub).' while executing '.$sql.n;
   		clean_exit($msg);
	}
	$user_list = rtrim($user_list,",");
	if ($user_list) {
		$sql = 'SELECT username, countryresident, countryorigin, orgtype FROM '.$metrics_db.'.'.$db_prefix.'xprofiles_metrics WHERE username IN ('.$user_list.')'; 
		$result = mysql_query($sql, $db_hub);
		if($result) {
			if(mysql_num_rows($result) > 0) {
  				while($row = mysql_fetch_assoc($result)) {
					if ($row[$r_param]) {
						$value = strtoupper($row[$r_param]);
						$sql_updt = 'UPDATE '.$table.' SET '.$param.' = '.dbquote($value).' WHERE ('.$param.' = "" OR '.$param.' IS NULL) AND user = '.dbquote($row['username']);
						mysql_exec($db_hub, $sql_updt);
					}
				}
			}
		} else {
			$msg = mysql_error($db_hub).' while executing '.$sql.n;
   			clean_exit($msg);
		}
	}
}

?>
