#!/usr/bin/php
<?php
# @package      hubzero-metrics
# @file         xlogfix_prep
# @author       Swaroop Shivarajapura Samek <swaroop@purdue.edu>
# @copyright    Copyright (c) 2011-2015 HUBzero Foundation, LLC.
# @license      http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
#
# Copyright (c) 2011-2015 HUBzero Foundation, LLC.
#
# This file is part of: The HUBzero(R) Platform for Scientific Collaboration
#
# The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
# software: you can redistribute it and/or modify it under the terms of
# the GNU Lesser General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# HUBzero is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# HUBzero is a registered trademark of HUBzero Foundation, LLC.
#
# =========================================================================
# This script creates an include file for the PERL scripts
#
# USAGE: ./xlogfix_setup
#

error_reporting(E_ALL & ~E_NOTICE);
@ini_set('display_errors','1');

if(!defined('__DIR__')) { 
    $fPos = strrpos(__FILE__, "/"); 
    define("__DIR__", substr(__FILE__, 0, $fPos) . "/"); 
} 

require_once(__DIR__."/includes/hub_parameters.php");

$file = __DIR__."/includes/access.cfg";

$fh = fopen($file, 'w') or die("can't open file");
$Data = "\$hub_dir = '".$hub_dir."';\n";
$Data .= "\$hub_db = '".trim($hub_db,'`')."';\n";
$Data .= "\$metrics_db = '".trim($metrics_db,'`')."';\n";
$Data .= "\$db_host = '".$db_host."';\n";
$Data .= "\$db_user = '".$db_user."';\n";
$Data .= "\$db_pass = '".$db_pass."';\n";
$Data .= "\$db_prefix = '".$db_prefix."';\n";
fwrite($fh, $Data); 
fclose($fh);

# Removing installation directory
$sh = "rm -rf ".$hub_dir."/installation";
// shell_exec($sh);

?>
