#!/usr/bin/php
<?php
# =========================================================================
# This script resolves host fields from ip address fields in various tables
#
# USAGE: ./xlogfix_dns <database> <table>
#
# =========================================================================
# AUTHOR: Swaroop Shivarajapura S, Purdue University
# Copyright (c) 2011 Purdue University
#
# BASED ON SIMILAR PERL SCRIPT BY: Swaroop Shivarajapura S, Purdue University
# and PHP SCRIPT by Nicholas Kisseberth, Purdue University
# =========================================================================

error_reporting(E_ALL & ~E_NOTICE);
@ini_set('display_errors','1');

if(!defined('__DIR__')) {
    $fPos = strrpos(__FILE__, "/");
    define("__DIR__", substr(__FILE__, 0, $fPos) . "/");
}

require_once(__DIR__."/includes/hub_parameters.php");
require_once(__DIR__."/includes/db_connect.php");
require_once(__DIR__."/includes/func_misc.php");

$timeout = 1;
$db_hub = db_connect('db_hub');

if (!$_SERVER['argv'][1] || !$_SERVER['argv'][2] || !$_SERVER['argv'][3] || !$_SERVER['argv'][4])
{
    $msg = 'Usage: ' . $_SERVER['argv'][0] . '<database> <table> <startdate> <enddate>'."\n";
    clean_exit($msg);
} else {
    $database = $_SERVER['argv'][1];
    $table = $_SERVER['argv'][2];
    $date = $_SERVER['argv'][3];
    $enddate = $_SERVER['argv'][4];
}

if ($database == 'hub') {
    $database = $hub_db;
} else if ($database == 'metrics') {
    $database = $metrics_db;
} else {
    $msg = 'Invalid database type'."\n";
    clean_exit($msg);
}

$sql = 'SELECT DISTINCT ip, host FROM '.$database.'.'.$table.' as w WHERE ip <> "" AND ip IS NOT NULL AND datetime > "'.$date.'" and datetime < "'.$enddate.'" AND (host = "" OR host = "?" OR host IS NULL)';
print "sql: $sql";
$result = mysqli_query($sql, $db_hub);
if($result) {
    if(mysqli_num_rows($result) > 0) {
        while($row = mysqli_fetch_row($result)) {
            echo "Looking up ".$row[0]." ".$timeout;
            $host = xgethostbyaddr($row[0], $timeout);
            if ($host == $row[0])
                $host = "?";
            # Update table record...
            if($row[1] != "?") {
                $sql_updt = 'UPDATE '.$database.'.'.$table.' SET host = '.dbquote($host).' WHERE (host = "" OR host = "?" OR host IS NULL) AND ip = '.dbquote($row[0]);
                print $sql_updt;
                mysqli_exec($db_hub, $sql_updt);
            }
        }
    }
} else {
    $msg = mysqli_error($db_hub).' while executing '.$sql."\n";
    clean_exit($msg);
}

db_close($db_hub);

?>
