#!/usr/bin/php
<?php
# @package      hubzero-metrics
# @file         xlogfix_user_info
# @author       Swaroop Shivarajapura <swaroop@purdue.edu>
# @copyright    Copyright (c) 2011-2014 HUBzero Foundation, LLC.
# @license      http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
#
# Copyright (c) 2011-2014 HUBzero Foundation, LLC.
#
# This file is part of: The HUBzero(R) Platform for Scientific Collaboration
#
# The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
# software: you can redistribute it and/or modify it under the terms of
# the GNU Lesser General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# HUBzero is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# HUBzero is a registered trademark of HUBzero Foundation, LLC.
#
# =========================================================================
# This Script assigns countryresident, countrycitizen and orgtype to each 
# user in toolstart table
#
# USAGE: ./xlogfix_user_info
#

error_reporting(E_ALL & ~E_NOTICE);
@ini_set('display_errors','1');

if(!defined('__DIR__')) {
    $fPos = strrpos(__FILE__, "/");
    define("__DIR__", substr(__FILE__, 0, $fPos) . "/");
}

require_once(__DIR__."/includes/hub_parameters.php");
require_once(__DIR__."/includes/db_connect.php");
require_once(__DIR__."/includes/func_misc.php");

$db_hub = db_connect('db_hub');

if (!$_SERVER['argv'][1] || !$_SERVER['argv'][2])
{
	$msg = 'Usage: ' . $_SERVER['argv'][0] . '<database>.<table>'.n;
	clean_exit($msg);
}

if ($_SERVER['argv'][1] == "hub") {
	$table = $hub_db.'.'.$_SERVER['argv'][2];
} else if ($_SERVER['argv'][1] == "metrics") {
	$table = $metrics_db.'.'.$_SERVER['argv'][2];
} else {
	$msg = 'Invalid database type'.n;
	clean_exit($msg);
}

$debug = 0;
$fix_params = array('countrycitizen','countryresident','orgtype');

foreach ($fix_params as $param) {
	update_tables($db_hub, $param, $table);
}

db_close($db_hub);

function update_tables($db_hub, $param, $table) {

	global $metrics_db, $db_prefix, $debug;	
	
	if ($debug)
		print "\n".'Finding all '.$table.' records lacking '.$param.'....'."\n";

	if ($param == "countrycitizen") {
		$r_param = "countryorigin";
	} else {
		$r_param = $param;
	}
	$user_list = '';
	$sql = 'SELECT DISTINCT user FROM '.$table.' WHERE ('.$param.' = "" OR '.$param.' IS NULL)';
	$result = mysql_query($sql, $db_hub);
	if($result) {
		if(mysql_num_rows($result) > 0) {
  			while($row = mysql_fetch_assoc($result)) {
				$user_list .= '"'.$row['user'].'",';
			}
		}
	} else {
		$msg = mysql_error($db_hub).' while executing '.$sql.n;
   		clean_exit($msg);
	}
	$user_list = rtrim($user_list,",");
	if ($user_list) {
		$sql = 'SELECT username, countryresident, countryorigin, orgtype FROM '.$metrics_db.'.'.$db_prefix.'xprofiles_metrics WHERE username IN ('.$user_list.')'; 
		$result = mysql_query($sql, $db_hub);
		if($result) {
			if(mysql_num_rows($result) > 0) {
  				while($row = mysql_fetch_assoc($result)) {
					if ($row[$r_param]) {
						$value = strtoupper($row[$r_param]);
						$sql_updt = 'UPDATE '.$table.' SET '.$param.' = '.dbquote($value).' WHERE ('.$param.' = "" OR '.$param.' IS NULL) AND user = '.dbquote($row['username']);
						mysql_exec($db_hub, $sql_updt);
					}
				}
			}
		} else {
			$msg = mysql_error($db_hub).' while executing '.$sql.n;
   			clean_exit($msg);
		}
	}
}

?>
