#!/usr/bin/php
<?php
# @package      hubzero-metrics
# @file         xlogfix_ipcountry
# @author       Swaroop Shivarajapura <swaroop@purdue.edu>
# @copyright    Copyright (c) 2011-2012 HUBzero Foundation, LLC.
# @license      http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
#
# Copyright (c) 2011-2012 HUBzero Foundation, LLC.
#
# This file is part of: The HUBzero(R) Platform for Scientific Collaboration
#
# The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
# software: you can redistribute it and/or modify it under the terms of
# the GNU Lesser General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# HUBzero is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# HUBzero is a registered trademark of HUBzero Foundation, LLC.
#
# ------------------------------------------------------------------------- 
# This script assigns assigns a country to IP addresses 
#
# USAGE: xlogfix_ipcountry <database> <table>
#

error_reporting(E_ALL & ~E_NOTICE);
@ini_set('display_errors','1');

if(!defined('__DIR__')) {
    $fPos = strrpos(__FILE__, "/");
    define("__DIR__", substr(__FILE__, 0, $fPos) . "/");
}

require_once(__DIR__."/includes/hub_parameters.php");
require_once(__DIR__."/includes/db_connect.php");
require_once(__DIR__."/includes/func_misc.php");

$db_hub = db_connect('db_hub');

if (!$_SERVER['argv'][1] || !$_SERVER['argv'][2])
{
	$msg = 'Usage: ' . $_SERVER['argv'][0] . '<database>.<table>'.n;
	clean_exit($msg);
} else {
	$database = $_SERVER['argv'][1];
	$table = $_SERVER['argv'][2];
}

if ($database == 'hub') {
	$database = $hub_db;
} else if ($database == 'metrics') {
	$database = $metrics_db;
} else {
	$msg = 'Invalid database type'.n;
	clean_exit($msg);
}

$sql = 'SELECT DISTINCT(INET_ATON(ip)) AS n_ip, COUNT(*) AS hits FROM '.$database.'.'.$table.' WHERE (ipcountry = "" OR ipcountry IS NULL) GROUP BY n_ip ORDER by hits desc;';
$result = mysql_query($sql, $db_hub);
if($result) {
	if(mysql_num_rows($result) > 0) {
  		while($row = mysql_fetch_assoc($result)) {
			$country = '';
			$n_ip = $row['n_ip'];
			$ip_geodata = get_ip_geodata($hubzero_ipgeo_url, $hub_key, $n_ip);
			if($ip_geodata['countrySHORT'] <> '') {
				$sql_updt = 'UPDATE '.$database.'.'.$table.' SET ipcountry= '.dbquote($ip_geodata['countrySHORT']).' WHERE INET_ATON(ip) = '.dbquote($n_ip).' AND (ipcountry = "" OR ipcountry IS NULL)';
				mysql_exec($db_hub, $sql_updt);
			}
		}
	}
} else {
	$msg = mysql_error($db_hub).' while executing '.$sql.n;
	clean_exit($msg);
}

db_close($db_hub);

?>
