#!/usr/bin/php
<?php
# @package      hubzero-metrics
# @file         xlogimport_tool_and_reg_user_data
# @author       Swaroop Shivarajapura Samek <swaroop@purdue.edu>
# @copyright    Copyright (c) 2011-2015 HUBzero Foundation, LLC.
# @license      http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
#
# Copyright (c) 2011-2015 HUBzero Foundation, LLC.
#
# This file is part of: The HUBzero(R) Platform for Scientific Collaboration
#
# The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
# software: you can redistribute it and/or modify it under the terms of
# the GNU Lesser General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# HUBzero is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# HUBzero is a registered trademark of HUBzero Foundation, LLC.
#
# =========================================================================
# This Script makes a copy of the HUB sessionlog table records into the
# metrics' sessionlog_metrics table and HUB jos_xprofiles table into metrics
# jos_xprofiles_metrics table.
#
# USAGE: ./xlogimport_tool_and_reg_user_data
#

error_reporting(E_ALL & ~E_NOTICE);
@ini_set('display_errors','1');

if(!defined('__DIR__')) {
    $fPos = strrpos(__FILE__, "/");
    define("__DIR__", substr(__FILE__, 0, $fPos) . "/");
}

require_once(__DIR__."/includes/hub_parameters.php");
require_once(__DIR__."/includes/db_connect.php");
require_once(__DIR__."/includes/func_misc.php");

$db_hub = db_connect('db_hub');

$sql = 'INSERT IGNORE INTO '.$metrics_db.'.sessionlog_metrics (sessnum, user, ip, start, appname) SELECT sessnum, username, remoteip, start, appname FROM '.$hub_db.'.sessionlog';
mysql_exec($db_hub, $sql);

$sql = 'DROP TABLE IF EXISTS '.$metrics_db.'.'.$db_prefix.'xprofiles_metrics';
mysql_exec($db_hub, $sql);

$sql = 'CREATE TABLE '.$metrics_db.'.'.$db_prefix.'xprofiles_metrics LIKE '.$hub_db.'.jos_xprofiles';
mysql_exec($db_hub, $sql);

$sql = 'INSERT INTO '.$metrics_db.'.'.$db_prefix.'xprofiles_metrics SELECT * FROM '.$hub_db.'.'.$db_prefix.'xprofiles WHERE emailConfirmed > 0';
mysql_exec($db_hub, $sql);

db_close($db_hub);

?>
