#!/usr/bin/php
<?php
# @package      hubzero-metrics
# @file         xlogimport_authlog
# @author       Nicholas J. Kisseberth <nkissebe@purdue.edu>
# @author       Swaroop Shivarajapura Samek <swaroop@purdue.edu>
# @copyright    Copyright (c) 2011-2015 HUBzero Foundation, LLC.
# @license      http://www.gnu.org/licenses/lgpl-3.0.html LGPLv3
#
# Copyright (c) 2011-2015 HUBzero Foundation, LLC.
#
# This file is part of: The HUBzero(R) Platform for Scientific Collaboration
#
# The HUBzero(R) Platform for Scientific Collaboration (HUBzero) is free
# software: you can redistribute it and/or modify it under the terms of
# the GNU Lesser General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# HUBzero is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# HUBzero is a registered trademark of HUBzero Foundation, LLC.
#
# ------------------------------------------------------------------------- 
# This Script imports information in the auth.log file into table userlogin
#
# USAGE: ./xlogimport_authlog <filename>
#
# NOTES: This script handles log files in the old and new formats
# 2007-05-17 11:06:39 username 128.210.189.195 login
# 2009-01-17 11:06:39 1234 [username] 128.210.189.195 login
#

error_reporting(E_ALL & ~E_NOTICE);
@ini_set('display_errors','1');

if(!defined('__DIR__')) {
    $fPos = strrpos(__FILE__, "/");
    define("__DIR__", substr(__FILE__, 0, $fPos) . "/");
}

require_once(__DIR__."/../includes/hub_parameters.php");
require_once(__DIR__."/../includes/db_connect.php");
require_once(__DIR__."/../includes/func_misc.php");

$db_hub = db_connect('db_hub');

$unrec = '';

$filehandle = fopen($_SERVER['argv'][1], "r");
if (!$filehandle) {
	$msg = "Error opening file: ".$_SERVER['argv'][1]."\n";
	clean_exit($msg);
}

# building excluded IP list
$filtered_ips = gen_exclude_list('ip');

$log_pattern_1 = '/^(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2}:\d{2})\s+([\d]+)\s+(\[.+\])\s+([\.\d]+)\s+([\w]+)$/';
$log_pattern_2 = '/^(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2}:\d{2})\s+(.+)\s+([\.\d]+)\s+([\w]+)$/';

while (1) {

	if (feof($filehandle))
		break;

	$line = fgets($filehandle);
	if (!$line) 
		break;

	if (preg_match($log_pattern_1, $line, $matches)) {
	    $datetime = $matches[1].' '.$matches[2];
		$uidNumber = trim($matches[3]);
		$user = rtrim(ltrim(trim($matches[4]),'['),']');
		$ip = trim($matches[5]);
		$action = trim($matches[6]);
    } else if ( preg_match($log_pattern_2, $line, $matches)) {
	    $datetime = $matches[1].' '.$matches[2];
		$uidNumber = 0;
		$user = trim($matches[3]);
		$ip = trim($matches[4]);
		$action = trim($matches[5]);
    } else {
    	$unrec .= 'Unrecognized format: '.$line;
		continue;
	}

	if ($user == "")
		$user = '-';

	if ($user <> "hubstatus" && $user <> "hubadmin" && (!search_array($ip, $filtered_ips))) {
		$sql_ins = 'INSERT IGNORE INTO '.$metrics_db.'.userlogin (datetime, uidNumber, user, ip, action) VALUES ('.dbquote($datetime).','.dbquote($uidNumber).','.dbquote($user).','.dbquote($ip).','.dbquote($action).')';
		mysql_exec($db_hub, $sql_ins);
	}
}

if ($unrec)
	print $unrec;

fclose($filehandle);
mysql_close($db_hub);

?>
